#ファームウェア作成のための材料調達リスト

manifest:#下の本家のzmkとトラックボールのドライバをどこから持ってくるのかを指定しているkumamuk-gitはトラックボール部分の持ってくるとこと推測しているあってるか不明
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
      
  projects:　#本家のzmkファームウェアを持ってくるようにバージョンは安定している０。３を持ってくるように
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml

      #トラックボール用のドライバを持ってくるという意味
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main

      #このファイルwest.ymlの立ち位置を決める文章config部分に入れてねという文章これがないとzmkがこのファイルがどこにあるのか見つけられなくなる（じゃあ全てにこういうの必要じゃないかと思った）
  self:
    path: config
